# .sync.yml
---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  os:
    - osx
  dist: '---'
  simplecov: true
  ruby_versions:
    - 2.6.3
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
  remove_branches:
    - master
  branches:
    - main
  user: vanagandr42
  secure: "J+IewhAvGn/VeN/x2A9PLpMkpXyTKcSmKAIoSCmCKoG+XsajgWSoFP9iiCSIMsGYNb1fh+WMq+DqQcK85Jqu1cBuVR5vY+ZMeoZBNU0ddsByfGdqx02kJFnX9o6mzwyja9JKnGIcOZCAM7+tINVP6ADPkYevciWV5OJvxUb8VnGHHV5ERovom+miBzaazIhQa+STAh7REO3ACO+c6XkozgYmvdNLcPnib9JPWvr4KOlqSSiqzt1wiu5RUyGSBkCVIwVzS6NqC7YOKU9QMYnQYhENuXrOseEyBeT3CnQuOFOVrOsEjdSN80OAKbKMdK5vlH10hNeLNE18zl0p18lyG/NUXQMMy2I12QFDYaeG+7m2r7rE1uExwP9OfWiFqPfsRRaIPtizhQz3g4fWx5zrFhA5HAgn9e9ieboaQ8s+jLapGRwPS9dMk6rsVKCFWFCCmzJBQ10ME+swa2Q6PkJbxFkiyW/iSW5XWdQ3yz30RUU50ihX4ggsKIvKiBJTQGeqCjLz1DxAoERrMLJzS2jlKm09cRqVmYXdyGbomH1l4jTkMfBk8wpAL+i8uVxMWq8rE30eLrEAJkAEr28RpJZpehTqR3OgOyZ0LymZgGEWBHPWuI3HeiDFvMBFQms95XuWfXTGFZlFpZHh5gykmV2nQVdhQ9okv8tKXBrsI8LSkus="
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'puppet-resource_api'
spec/spec_helper.rb:
  mock_with: ':rspec'
